export const LOGIN_BEGINS = 'LOGIN_BEGINS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILS = 'LOGIN_FAILS';

export const LOGOUT_BEGINS = 'LOGOUT_BEGINS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILS = 'LOGOUT_FAILS';

export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';

export const GET_USER_LIST_BEGINS = 'GET_USER_LIST_BEGINS';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILS = 'GET_USER_LIST_FAILS';